global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-microsoft-activedirectory
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
tests:
  template1:
    parameter_input: Template_1_AD_2012R2.json
    regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - eu-central-1
      - eu-west-1
    #  - sa-east-1 NAT Gateway not available
      - us-east-1
      - us-west-1
      - us-west-2
    template_file: Template_1_AD_2012R2.template
  template2:
    parameter_input: Template_2_AD_2012R2.json
    regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - eu-central-1
      - eu-west-1
    #  - sa-east-1 NAT Gateway not available
      - us-east-1
      - us-west-1
      - us-west-2
    template_file: Template_2_AD_2012R2.template
  template3:
    parameter_input: Template_3_AD_2012R2.json
    # Execute only in regions that support AWS Directory Service for Microsoft AD
    regions:
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
      - eu-central-1
      - eu-west-1
      - us-east-1
      - us-west-2
    template_file: Template_3_AD_2012R2.template
  master1:
    parameter_input: ad-master-1.json
    template_file: ad-master-1.template
  master2:
    parameter_input: ad-master-2.json
    template_file: ad-master-2.template
  master3:
    parameter_input: ad-master-3.json
    # Execute only in regions that support AWS Directory Service for Microsoft AD
    regions:
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
      - eu-central-1
      - eu-west-1
      - us-east-1
      - us-west-2
    template_file: ad-master-3.template
