global:
  qsname: quickstart-microsoft-activedirectory
  reporting: true
  cis3bucket: s3://quickstart-ci-bucket
  regions:
    - us-east-1
    - us-west-1
    - eu-west-1
    - us-west-2
    - sa-east-1
    - eu-central-1
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-2

tests:
  qs_msadt1:
    template_file: Template_1_AD_2012R2.template
    parameter_input: Template_1_AD_2012R2.json
